version: '3.3'

services:
  web:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    links:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=delivery

# uncomment to use persistent storage
#    volumes:
#      - $HOME/volumes_backups/food_delivery:/var/lib/postgresql/data